### ISSUE TITLE
exporter does not work with current version of blender 2.8

### ISSUE THREAD

**Issue by GBrent-dev** [supermedium/aframe-particleplayer-component#8]
I'm getting this error when saving.  I've selected the emitter object and the am only trying to render a 30 frames of a 150 frame particle animation.

Traceback (most recent call last):
  File "C:\Users\Riel\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\particleplayer.py", line 175, in execute
    return export_main(context, self.filepath, settings, self)
  File "C:\Users\Riel\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\particleplayer.py", line 59, in export_main
    obj = bpy.context.depsgraph.objects.get(obj.name, None)
AttributeError: 'Context' object has no attribute 'depsgraph'

location: <unknown location>:-1

**Comment by lijualivenow** [comment]
We are waiting for this bug fix. 2.8x plugin is not working on any blender version. Other plug in is working with 2.79 blender.
